'use client'

import { useEffect, useState } from 'react'
import { useRouter, useParams } from 'next/navigation'
import Link from 'next/link'
import { MobileShell } from '@/components/layout/MobileShell'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { ProgressThread } from '@/components/ui/ProgressThread'
import { FACILITIES } from '@/content/facilities'
import {
  initJourney,
  advanceStage,
  updateJourneyState,
  getJourneyState,
} from '@/lib/journey/tracker'
import { createClient } from '@/lib/supabase/client'

export default function ReferralPage() {
  const router = useRouter()
  const params = useParams()
  const facilityId = params?.id as string

  const [saved, setSaved] = useState(false)
  const [referralId, setReferralId] = useState<string | null>(null)

  const facility = FACILITIES.find((f) => f.id === facilityId)

  useEffect(() => {
    if (!facility) return
    initJourney()
    advanceStage('REFERRED')

    const state = getJourneyState()
    if (!state) return

    // Save referral to Supabase — fire and forget
    const supabase = createClient()
    supabase
      .from('referrals')
      .insert({
        journey_id: state.journeyId,
        facility_id: facility.id,
        facility_name: facility.name,
        facility_state: facility.state,
        facility_phone: facility.phone,
      })
      .select('id')
      .single()
      .then(({ data }) => {
        if (data?.id) {
          setReferralId(data.id)
          updateJourneyState({ referralId: data.id })
        }
      })
  }, [facility])

  async function handleSave() {
    const text = `My breast screening referral\n\n${facility?.name}\n${facility?.address}\n${facility?.phone}\n${facility?.openingHours}\n\nWhat to say: "I am here for a breast screening."\n\nWhat to bring: Valid ID, comfortable clothing, any previous results if available.\n\nGenerated by Project Bloom — bloom.clarit.studio`

    if (navigator.share) {
      try {
        await navigator.share({ title: 'My Screening Referral', text })
        setSaved(true)
      } catch {
        // User cancelled share — not an error
      }
    } else {
      await navigator.clipboard.writeText(text)
      setSaved(true)
    }
  }

  function handleWhatsApp() {
    const text = encodeURIComponent(
      `I am going for a breast screening at ${facility?.name} (${facility?.address}). Wish me well 🌸`
    )
    window.open(`https://wa.me/?text=${text}`, '_blank')
  }

  if (!facility) {
    return (
      <MobileShell>
        <div className="pt-16 text-center">
          <p className="font-display text-bloom-text text-[1.4rem] mb-4">
            We could not find that clinic
          </p>
          <p className="text-bloom-muted text-[17px] mb-8">
            Please go back and select a facility from the list.
          </p>
          <Link href="/facilities">
            <Button variant="primary">← Find a clinic</Button>
          </Link>
        </div>
      </MobileShell>
    )
  }

  return (
    <MobileShell>
      <ProgressThread currentStage="REFERRED" />

      {/* Top nav */}
      <div className="pt-10 pb-6 flex items-center gap-3">
        <button
          onClick={() => router.back()}
          className="text-bloom-muted text-sm underline"
        >
          ← Back
        </button>
      </div>

      {/* Header */}
      <div className="mb-6">
        <span className="inline-block text-xs font-semibold text-bloom-primary bg-bloom-primary/10 rounded-full px-3 py-1 mb-3">
          Your referral is ready
        </span>
        <h1 className="font-display text-bloom-text text-[1.75rem] leading-tight">
          You are ready to go
        </h1>
        <p className="text-bloom-muted text-[17px] mt-2">
          You already know what to expect. Here is everything you need for your visit.
        </p>
      </div>

      {/* Facility card */}
      <Card className="mb-4">
        <h2 className="font-display text-bloom-text text-[1.3rem] leading-snug mb-3">
          {facility.name}
        </h2>
        <p className="text-bloom-muted text-sm mb-1">📍 {facility.address}</p>
        <p className="text-bloom-muted text-sm mb-1">🕐 {facility.openingHours}</p>
        <p className="text-bloom-text text-[17px] font-semibold mt-3">
          📞 {facility.phone}
        </p>
      </Card>

      {/* What to say */}
      <Card className="mb-4">
        <h3 className="font-display text-bloom-text text-[1.1rem] mb-2">
          What to say when you call
        </h3>
        <p className="text-bloom-text text-[17px] leading-relaxed italic">
          &ldquo;I am calling to book a breast screening appointment.&rdquo;
        </p>
      </Card>

      {/* What to bring */}
      <Card className="mb-4">
        <h3 className="font-display text-bloom-text text-[1.1rem] mb-3">
          What to bring
        </h3>
        <ul className="space-y-2">
          {[
            'A valid ID (NIN slip, voter card, or any ID)',
            'Comfortable clothing you can easily adjust',
            'Any previous breast examination results, if you have them',
          ].map((item) => (
            <li key={item} className="flex items-start gap-3 text-bloom-text text-[17px]">
              <span className="text-bloom-gold mt-1">✓</span>
              <span>{item}</span>
            </li>
          ))}
        </ul>
      </Card>

      {/* Reminder */}
      <Card className="mb-8 border-bloom-primary/20 bg-bloom-primary/5">
        <p className="text-bloom-text text-[17px] leading-relaxed">
          You have already read through what will happen when you get there.{' '}
          <Link href="/expect" className="text-bloom-primary underline">
            Read it again
          </Link>{' '}
          if you want to feel even more prepared.
        </p>
      </Card>

      {/* Primary action */}
      <Button variant="primary" onClick={handleSave} className="mb-4">
        {saved ? '✓ Saved to your phone' : 'Save this referral →'}
      </Button>

      {/* WhatsApp share — text link, not competing button */}
      <p className="text-center text-bloom-muted text-sm">
        or{' '}
        <button
          onClick={handleWhatsApp}
          className="text-bloom-whatsapp underline font-medium"
        >
          share on WhatsApp
        </button>
      </p>
    </MobileShell>
  )
}
